require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ConceptsController do

  # This should return the minimal set of attributes required to create a valid
  # Concept. As you add validations to Concept, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { :name => "FooBar"}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ConceptsController. Be sure to keep this updated too.
  def valid_session
    { }
  end

describe 
  describe "GET index" do
    it "assigns all concepts as @concepts" do
      concept =FactoryGirl.create(:concept) 
      get :index, {}, valid_session
      assigns(:concepts).should eq([concept])
    end
  end

  describe "GET show" do
    it "assigns the requested concept as @concept" do
      concept = FactoryGirl.create(:concept) 
      get :show, {:id => concept.to_param}, valid_session
      assigns(:concept).should eq(concept)
    end
  end

  describe "GET new" do
    it "assigns a new concept as @concept" do
      get :new, {}, valid_session
      assigns(:concept).should be_a_new(Concept)
    end
  end

  describe "GET edit" do
    login_admin
    it "assigns the requested concept as @concept" do
      concept = FactoryGirl.create(:concept)
      get :edit, {:id => concept.to_param }, valid_session
      assigns(:concept).should eq(concept)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      login_admin
      it "creates a new Concept" do
        expect {
          post :create, { :concept => valid_attributes}, valid_session
        }.to change(Concept, :count).by(1)
      end

      it "assigns a newly created concept as @concept" do
        post :create, {:concept => valid_attributes}, valid_session
        assigns(:concept).should be_a(Concept)
        assigns(:concept).should be_persisted
      end

      it "redirects to the created concept" do
        post :create, {:concept => valid_attributes}, valid_session
        response.should redirect_to(Concept.all.to_a.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved concept as @concept" do
        # Trigger the behavior that occurs when invalid params are submitted
        Concept.any_instance.stub(:save).and_return(false)
        post :create, {:concept => {}}, valid_session
        assigns(:concept).should be_a_new(Concept)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Concept.any_instance.stub(:save).and_return(false)
        post :create, {:concept => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested concept" do
        concept =FactoryGirl.create(:concept) 
        # Assuming there are no other concepts in the database, this
        # specifies that the Concept created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Concept.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => concept.to_param, :concept => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested concept as @concept" do
        concept =FactoryGirl.create(:concept) 
        put :update, {:id => concept.to_param, :concept => valid_attributes}, valid_session
        assigns(:concept).should eq(concept)
      end

      it "redirects to the concept" do
        concept =FactoryGirl.create(:concept) 
        put :update, {:id => concept.to_param, :concept => valid_attributes}, valid_session
        response.should redirect_to(concept)
      end
    end

    describe "with invalid params" do
      it "assigns the concept as @concept" do
        concept =FactoryGirl.create(:concept) 
        # Trigger the behavior that occurs when invalid params are submitted
        Concept.any_instance.stub(:save).and_return(false)
        put :update, {:id => concept.to_param, :concept => {}}, valid_session
        assigns(:concept).should eq(concept)
      end

      it "re-renders the 'edit' template" do
        concept =FactoryGirl.create(:concept) 
        # Trigger the behavior that occurs when invalid params are submitted
        Concept.any_instance.stub(:save).and_return(false)
        put :update, {:id => concept.to_param, :concept => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested concept" do
      concept =FactoryGirl.create(:concept) 
      expect {
        delete :destroy, {:id => concept.to_param}, valid_session
      }.to change(Concept, :count).by(-1)
    end

    it "redirects to the concepts list" do
      concept =FactoryGirl.create(:concept) 
      delete :destroy, {:id => concept.to_param}, valid_session
      response.should redirect_to(concepts_url)
    end
  end

end
