require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CorporateBodiesController do

  # This should return the minimal set of attributes required to create a valid
  # CorporateBody. As you add validations to CorporateBody, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CorporateBodiesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all corporate_bodies as @corporate_bodies" do
      corporate_body = CorporateBody.create! valid_attributes
      get :index, {}, valid_session
      assigns(:corporate_bodies).should eq([corporate_body])
    end
  end

  describe "GET show" do
    it "assigns the requested corporate_body as @corporate_body" do
      corporate_body = CorporateBody.create! valid_attributes
      get :show, {:id => corporate_body.to_param}, valid_session
      assigns(:corporate_body).should eq(corporate_body)
    end
  end

  describe "GET new" do
    it "assigns a new corporate_body as @corporate_body" do
      get :new, {}, valid_session
      assigns(:corporate_body).should be_a_new(CorporateBody)
    end
  end

  describe "GET edit" do
    it "assigns the requested corporate_body as @corporate_body" do
      corporate_body = CorporateBody.create! valid_attributes
      get :edit, {:id => corporate_body.to_param}, valid_session
      assigns(:corporate_body).should eq(corporate_body)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CorporateBody" do
        expect {
          post :create, {:corporate_body => valid_attributes}, valid_session
        }.to change(CorporateBody, :count).by(1)
      end

      it "assigns a newly created corporate_body as @corporate_body" do
        post :create, {:corporate_body => valid_attributes}, valid_session
        assigns(:corporate_body).should be_a(CorporateBody)
        assigns(:corporate_body).should be_persisted
      end

      it "redirects to the created corporate_body" do
        post :create, {:corporate_body => valid_attributes}, valid_session
        response.should redirect_to(CorporateBody.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved corporate_body as @corporate_body" do
        # Trigger the behavior that occurs when invalid params are submitted
        CorporateBody.any_instance.stub(:save).and_return(false)
        post :create, {:corporate_body => {}}, valid_session
        assigns(:corporate_body).should be_a_new(CorporateBody)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CorporateBody.any_instance.stub(:save).and_return(false)
        post :create, {:corporate_body => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested corporate_body" do
        corporate_body = CorporateBody.create! valid_attributes
        # Assuming there are no other corporate_bodies in the database, this
        # specifies that the CorporateBody created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CorporateBody.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => corporate_body.to_param, :corporate_body => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested corporate_body as @corporate_body" do
        corporate_body = CorporateBody.create! valid_attributes
        put :update, {:id => corporate_body.to_param, :corporate_body => valid_attributes}, valid_session
        assigns(:corporate_body).should eq(corporate_body)
      end

      it "redirects to the corporate_body" do
        corporate_body = CorporateBody.create! valid_attributes
        put :update, {:id => corporate_body.to_param, :corporate_body => valid_attributes}, valid_session
        response.should redirect_to(corporate_body)
      end
    end

    describe "with invalid params" do
      it "assigns the corporate_body as @corporate_body" do
        corporate_body = CorporateBody.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CorporateBody.any_instance.stub(:save).and_return(false)
        put :update, {:id => corporate_body.to_param, :corporate_body => {}}, valid_session
        assigns(:corporate_body).should eq(corporate_body)
      end

      it "re-renders the 'edit' template" do
        corporate_body = CorporateBody.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CorporateBody.any_instance.stub(:save).and_return(false)
        put :update, {:id => corporate_body.to_param, :corporate_body => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested corporate_body" do
      corporate_body = CorporateBody.create! valid_attributes
      expect {
        delete :destroy, {:id => corporate_body.to_param}, valid_session
      }.to change(CorporateBody, :count).by(-1)
    end

    it "redirects to the corporate_bodies list" do
      corporate_body = CorporateBody.create! valid_attributes
      delete :destroy, {:id => corporate_body.to_param}, valid_session
      response.should redirect_to(corporate_bodies_url)
    end
  end

end
